"""Adapters used by the section 17 end-to-end scenarios.

``base`` holds the contracts the scenarios are written against; ``mock`` holds
the offline implementations. A real backend plugs in by satisfying
``base.AgentAdapter`` and overriding the ``agent`` fixture in ``conftest.py``.
"""

from .base import (
    ADMIN,
    DEFAULT_ADAPTER_NAME,
    EMPLOYEE,
    HR,
    ROLE_ADMIN,
    ROLE_EMPLOYEE,
    ROLE_HR,
    ROUTE_ACTION,
    ROUTE_DB,
    ROUTE_NONE,
    ROUTE_RAG,
    STATUS_DENIED,
    STATUS_NEEDS_CLARIFICATION,
    STATUS_NEEDS_CONFIRMATION,
    STATUS_OK,
    VICTIM,
    AgentAdapter,
    AgentReply,
    AgentSession,
    AuditAdapter,
    AuditEntry,
    Chunk,
    HrmsAdapter,
    PermissionAdapter,
    RetrieverAdapter,
)
from .mock import (
    INTENT_ACTIONS,
    PERMISSION_MATRIX,
    AuditLog,
    InMemoryHrms,
    MockAgent,
    MockAgentSession,
    MockClock,
    MockPermissions,
    MockRetriever,
)
from .world import Datasets

__all__ = [
    "ADMIN",
    "DEFAULT_ADAPTER_NAME",
    "EMPLOYEE",
    "HR",
    "VICTIM",
    "ROLE_ADMIN",
    "ROLE_EMPLOYEE",
    "ROLE_HR",
    "ROUTE_ACTION",
    "ROUTE_DB",
    "ROUTE_NONE",
    "ROUTE_RAG",
    "STATUS_DENIED",
    "STATUS_NEEDS_CLARIFICATION",
    "STATUS_NEEDS_CONFIRMATION",
    "STATUS_OK",
    "AgentAdapter",
    "AgentReply",
    "AgentSession",
    "AuditAdapter",
    "AuditEntry",
    "Chunk",
    "Datasets",
    "HrmsAdapter",
    "INTENT_ACTIONS",
    "InMemoryHrms",
    "AuditLog",
    "MockAgent",
    "MockAgentSession",
    "MockClock",
    "MockPermissions",
    "MockRetriever",
    "PERMISSION_MATRIX",
    "PermissionAdapter",
    "RetrieverAdapter",
]
